### ISSUE TITLE
Add support for JDK 11

### ISSUE THREAD

**Issue by rbreslow** [geotrellis/maml#100]
Right now, tests are failing on JDK 11. We should:

- Add support for JDK 11
- Ensure tests are passing on JDK 11
- Add JDK 11 to the CI matrix

See: https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html#jdk-11-compatibility-notes

**Comment by pomadchin** [comment]
@rbreslow the usual way is to build things against `jdk 8` and to run it on `9, 10, 11, graal-vm` (usually it works. Scala doesn't have a full `>8 JDK`s support ).
I am not sure that it's the thing to aim now, since there are some compiler limitations.

**Comment by pomadchin** [comment]
Closed via https://github.com/geotrellis/maml/pull/126
